language: php

sudo: false

php:
  - 5.3
  - 5.5

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update

install:
  - composer install --prefer-dist

before_script:
  - git config --global user.email "travis-ci@codeclimate.com"
  - git config --global user.name "Travis CI"

script:
  - vendor/bin/phpunit

after_script:
  - php composer/bin/test-reporter
